name: boombet_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  jwt_decoder: ^2.0.1
  web_socket_channel: ^3.0.1
  go_router: ^14.0.0
  flutter_html: ^3.0.0-beta.2
  cached_network_image: ^3.3.0
  flame: ^1.34.0
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.2.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/app_icon.png"
  image_path_ios: "assets/icons/app_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  remove_alpha_ios: true

flutter_app_name:
  name: "BoomBet"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/games/game_01/sprites/
    - assets/images/games/game_01/backgrounds/
    - assets/images/games/game_01/obstacles/

flutter_native_splash:
  color: "#000000"
  image: "assets/icons/splash_icon.png"

  android: true
  ios: true

  android_12:
    color: "#000000"
    image: "assets/icons/splash_icon.png"
